export const playersData = {
  description:
    "Browse players by division, search by name or FIDE ID, and filter by category or federation.",
  divisions: ["U8", "U10", "U12", "U14", "U16", "U18", "U20"],
  categories: ["Open", "Girls"] as const,
  players: [
    { name: "Ari Tan", division: "U8", category: "Open", federation: "AUS", flag: "AU", fideId: "52000101", fideRating: 1120 },
    { name: "Lucas Wei", division: "U8", category: "Open", federation: "NZL", flag: "NZ", fideId: "43000102", fideRating: 1087 },
    { name: "Mila Kumar", division: "U8", category: "Girls", federation: "FIJ", flag: "FJ", fideId: "91000103", fideRating: 1042 },
    { name: "Sophie Teo", division: "U10", category: "Girls", federation: "SGP", flag: "SG", fideId: "58000104", fideRating: 1298 },
    { name: "Noah Faumuina", division: "U10", category: "Open", federation: "SAM", flag: "WS", fideId: "99000105", fideRating: 1214 },
    { name: "Ethan Ho", division: "U10", category: "Open", federation: "AUS", flag: "AU", fideId: "52000106", fideRating: 1355 },
    { name: "Chloe Martin", division: "U12", category: "Girls", federation: "NZL", flag: "NZ", fideId: "43000107", fideRating: 1512 },
    { name: "Ryan Lim", division: "U12", category: "Open", federation: "MAS", flag: "MY", fideId: "57000108", fideRating: 1590 },
    { name: "Isla Prasad", division: "U12", category: "Open", federation: "FIJ", flag: "FJ", fideId: "91000109", fideRating: 1468 },
    { name: "Emily Stone", division: "U14", category: "Girls", federation: "AUS", flag: "AU", fideId: "52000110", fideRating: 1718 },
    { name: "Daniel Reddy", division: "U14", category: "Open", federation: "NZL", flag: "NZ", fideId: "43000111", fideRating: 1774 },
    { name: "Mia Vuniyayawa", division: "U14", category: "Girls", federation: "FIJ", flag: "FJ", fideId: "91000112", fideRating: 1630 },
    { name: "James Patel", division: "U16", category: "Open", federation: "AUS", flag: "AU", fideId: "52000113", fideRating: 1936 },
    { name: "Grace Niu", division: "U16", category: "Girls", federation: "NZL", flag: "NZ", fideId: "43000114", fideRating: 1824 },
    { name: "Tyler Sione", division: "U16", category: "Open", federation: "TGA", flag: "TO", fideId: "98000115", fideRating: 1882 },
    { name: "Sarah Wong", division: "U18", category: "Girls", federation: "SGP", flag: "SG", fideId: "58000116", fideRating: 2011 },
    { name: "Oliver Chen", division: "U18", category: "Open", federation: "AUS", flag: "AU", fideId: "52000117", fideRating: 2094 },
    { name: "Hana Moce", division: "U18", category: "Girls", federation: "FIJ", flag: "FJ", fideId: "91000118", fideRating: 1916 },
    { name: "Leo Thompson", division: "U20", category: "Open", federation: "NZL", flag: "NZ", fideId: "43000119", fideRating: 2217 },
    { name: "Amelia Cruz", division: "U20", category: "Girls", federation: "AUS", flag: "AU", fideId: "52000120", fideRating: 2068 },
    { name: "Ben Tavita", division: "U20", category: "Open", federation: "SAM", flag: "WS", fideId: "99000121", fideRating: 2145 },
  ],
};
